name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: SimpleIrcLib/SimpleIRCLib.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: SimpleIrcLib-TheUltimateC0der
        # API key to authenticate with NuGet server
        NUGET_KEY: oy2mllbfvoaxi6utazeaxpgnu7bqmlnuvawgnlyzvmdlru
      
